/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import codes.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Isuru Gayan
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
   
    
    public login() {
        initComponents();
        conn=DBConnect.dbconnect();
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pword = new javax.swing.JPasswordField();
        admin = new javax.swing.JButton();
        cashiers = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("login");
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Health Medicare Pharmacy");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 670, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 210, 30));

        pword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 210, 30));

        admin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isuru Gayan\\Documents\\NetBeansProjects\\project5\\images\\admin.png")); // NOI18N
        admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 300, 310));

        cashiers.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isuru Gayan\\Documents\\NetBeansProjects\\project5\\images\\cashiers.png")); // NOI18N
        cashiers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cashiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashiersActionPerformed(evt);
            }
        });
        jPanel1.add(cashiers, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 300, 280));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Admin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Cashier");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isuru Gayan\\Documents\\NetBeansProjects\\project5\\images\\login.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        setSize(new java.awt.Dimension(1218, 847));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        String userName=null;
        String password=null;
        
        userName=uname.getText();
        password=pword.getText();
        
        try {
                String sql="select * from admin";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
            
                int log=0;
                while(rs.next())
                {
                    if(rs.getString(1).equals(userName)&&rs.getString(2).equals(password))
                    {
                        log=1;
                        break;
                    }
                }
            
                if(log==1)
                {
                    //JOptionPane.showMessageDialog(null,"success");
                    this.dispose();
                    waitingBarr w=new waitingBarr(1);
                    w.setVisible(true);
                    //adminMain obj=new adminMain();
                    //obj.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"login failed");
                }
            }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"sql error");
         }
    }//GEN-LAST:event_adminActionPerformed

    private void cashiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashiersActionPerformed
        String userName=null;
        String password=null;
        
        userName=uname.getText();
        password=pword.getText();
        
        try {
            String sql="select * from cashiers";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            int log=0;
            while(rs.next())
            {
                if(rs.getString(8).equals(userName)&&rs.getString(9).equals(password))
                {
                    log=1;
                    break;
                }
            }
            
            if(log==1)
            {
                //JOptionPane.showMessageDialog(null,"success");
                
                waitingBarr obj=new waitingBarr(2,userName);
                obj.setVisible(true);
                this.dispose();
                //cashierMain obj=new cashierMain();
                //obj.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"login failed");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"sql error");
        }
    }//GEN-LAST:event_cashiersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton cashiers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pword;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
