/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;



import codes.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Isuru Gayan
 */
public class receipt extends javax.swing.JFrame {

    int invoiceId;
    float total;
    float payment;
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    public receipt(int invoiceId,float total,float payment) {
        initComponents();
        conn=DBConnect.dbconnect();
        this.invoiceId=invoiceId;
        this.total=total;
        this.payment=payment;
        texttArea();
    }
    
    public void texttArea()
    {
        Date obj=new Date();
        String date=obj.toString();
        
        receipt.setText("         HEALTH MEDICARE PHARMACY\n");
        receipt.setText(receipt.getText()+"          Tel-phone : 0755375315\n");
        receipt.setText(receipt.getText()+"       "+date+"\n");
        receipt.setText(receipt.getText()+"*******************************************\n");
        receipt.setText(receipt.getText()+"               CASH RECEIPT                \n");
        receipt.setText(receipt.getText()+"*******************************************\n");
        receipt.setText(receipt.getText()+"Description        Quantity           Price\n");
        try {
            String sql="select m.medicine_name,t.quantity,t.price from transaction t join medicine m using(medicine_id) where t.invoice_id='"+invoiceId+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next())
            {
                receipt.setText(receipt.getText()+rs.getString(1)+"          "+rs.getString(2)+"            "+rs.getString(3)+"\n");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"sql Error");
        }
        
        receipt.setText(receipt.getText()+"*******************************************\n");
        receipt.setText(receipt.getText()+"Total                               "+total+"\n");
        receipt.setText(receipt.getText()+"Cash                                "+payment+"\n");
        receipt.setText(receipt.getText()+"Change                              "+String.valueOf(payment-total)+"\n");
        receipt.setText(receipt.getText()+"                Thank You..!!\n");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirm = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Receipt");
        setMinimumSize(new java.awt.Dimension(800, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirm.setBackground(new java.awt.Color(0, 102, 102));
        confirm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receipt.setColumns(20);
        receipt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        receipt.setRows(5);
        jScrollPane1.setViewportView(receipt);

        confirm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 490, 510));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        confirm.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, -1, -1));

        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));

        setSize(new java.awt.Dimension(800, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            receipt.print();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Print Fail");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt(0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea receipt;
    // End of variables declaration//GEN-END:variables
}
